function tw (){
  touch $*
  open -a /Applications/TextWrangler.app $*
}

alias mark="echo ============================================================================================================================================================================================================================================================="

HISTSIZE=50000
HISTFILESIZE=100000
HISTIGNORE="&:[ ]*:exit"
shopt -s histappend
PROMPT_COMMAND="history -a"

alias gitc='git log --oneline --abbrev-commit --all --graph --decorate --color'

export JAVA_HOME=`/usr/libexec/java_home`

for x in ~/.completion/*; do . $x ; done
for x in ~/.profile/*; do . $x ; done

PS1="\$(if [[ \$EUID == 0 ]];then \"\[\033[0;31m\]\"; else echo \"\[\033[0;00m\]\";fi)[\!] \t \u@\h \w \$(if [[ \$? == 0 ]]; then echo \"\[\033[0;32m\]\"; else echo \"\[\033[0;31m\]\"; fi)\$\[\033[00m\]"
